[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = [
  "pnpm --filter @starline/database generate",
  "pnpm --filter @starline/api build"
]

[start]
cmd = "pnpm --filter @starline/api start"